spring.application.name=OAuth
spring.security.oauth2.client.registration.google.client-id=511560088107-hnagrvqm1s6d86tsh1msbnfpugu1rfo6.apps.googleusercontent.com

spring.security.oauth2.client.registration.google.client-secret=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